language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
  - eval "${MATRIX_EVAL}"
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
  - cmake .
  - cmake --build .
  - build/tests/async_test
  - build/tests/mt_test
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandreyandreevich:$BINTRAY_API_KEY "https://api.bintray.com/content/12345678/cpp_projects/async/$TRAVIS_BUILD_NUMBER/async-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
